{"name": "调试运算新功能,从响应提取后运算", "status": "failed", "statusDetails": {"message": "AssertionError: 第1个断言失败 -|- 实际结果:用户名已存在 || 预期结果: 成功", "trace": "cls = <class 'tools.data_process.DataProcess'>\nresponse = {'data': None, 'meta': {'msg': '用户名已存在', 'status': 400}}\nexpect_str = '{\"$.meta.msg\": \"成功\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        allure_step(\"当前可用参数池\", cls.extra_pool)\n        expect_str = rep_expr(expect_str, cls.extra_pool)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(\n                f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言', f'实际结果:{actual} = 预期结果:{v}')\n            try:\n>               assert actual == v\nE               AssertionError\n\ntools\\data_process.py:133: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ncases = ['c18', '调试运算新功能,从响应提取后运算', '{\"Authorization\": \"${token}\"}', 'users/', 'post', 'data', ...]\n\n    def test_main(cases):   # 不使用数据库功能\n        # 发送请求\n        response, expect, sql = client.action(cases)\n        # 断言操作\n>       DataProcess.assert_result(response, expect)\n\ntest\\test_api.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tools.data_process.DataProcess'>\nresponse = {'data': None, 'meta': {'msg': '用户名已存在', 'status': 400}}\nexpect_str = '{\"$.meta.msg\": \"成功\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        allure_step(\"当前可用参数池\", cls.extra_pool)\n        expect_str = rep_expr(expect_str, cls.extra_pool)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(\n                f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言', f'实际结果:{actual} = 预期结果:{v}')\n            try:\n                assert actual == v\n            except AssertionError:\n>               raise AssertionError(\n                    f'第{index}个断言失败 -|- 实际结果:{actual} || 预期结果: {v}')\nE               AssertionError: 第1个断言失败 -|- 实际结果:用户名已存在 || 预期结果: 成功\n\ntools\\data_process.py:135: AssertionError"}, "steps": [{"name": "请求地址: http://api.zreai.com:606/api/private/v1/users/", "status": "passed", "start": 1640080924814, "stop": 1640080924814}, {"name": "请求头", "status": "passed", "attachments": [{"name": "请求头", "source": "b702e57d-fca0-4458-97ab-320db652e4ca-attachment.json", "type": "application/json"}], "start": 1640080924814, "stop": 1640080924814}, {"name": "请求数据", "status": "passed", "attachments": [{"name": "请求数据", "source": "b84ed6c1-e10a-42f4-91e7-31793b55b957-attachment.json", "type": "application/json"}], "start": 1640080924814, "stop": 1640080924814}, {"name": "响应耗时(s): 0.036692", "status": "passed", "start": 1640080924846, "stop": 1640080924846}, {"name": "响应结果", "status": "passed", "attachments": [{"name": "响应结果", "source": "c7cefb62-8bd5-47fc-a7af-b9cb3ad67e27-attachment.json", "type": "application/json"}], "start": 1640080924846, "stop": 1640080924846}, {"name": "当前可用参数池", "status": "passed", "attachments": [{"name": "当前可用参数池", "source": "1a47949c-d48f-46a8-84c5-84a00e6be08c-attachment.json", "type": "application/json"}], "start": 1640080924846, "stop": 1640080924846}, {"name": "第1个断言", "status": "passed", "attachments": [{"name": "第1个断言", "source": "d572abba-bb58-45d3-bf84-3e0b01d8abb2-attachment.json", "type": "application/json"}], "start": 1640080924846, "stop": 1640080924846}], "parameters": [{"name": "cases", "value": "['c18', '调试运算新功能,从响应提取后运算', '{\"Authorization\": \"${token}\"}', 'users/', 'post', 'data', '', '{\"username\": \"tery\",\"password\": ${get_current_highest()}}', '', '', '{\"$.meta.msg\": \"成功\"}']"}], "start": 1640080924814, "stop": 1640080924846, "uuid": "981ada70-bd86-4505-b400-41d9eba8104a", "historyId": "25f6ba9e78828713a480fcdbed4cfa82", "testCaseId": "881516e7ef2e2aa5436f6a3c3e6a5bcb", "fullName": "test.test_api#test_main", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-CJL4PLI"}, {"name": "thread", "value": "14256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}]}